stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker-build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - sudo docker-compose -f deploy/docker-compose.yml build
    - sudo docker tag gf-test:latest 192.168.10.100:5000/gf-test:$CI_COMMIT_SHORT_SHA
    - sudo docker push 192.168.10.100:5000/gf-test:$CI_COMMIT_SHORT_SHA

deploy_Integration:
  stage: deploy
  tags:
    - vrpower
  script:
    - sudo env CI_COMMIT_SHORT_SHA="${CI_COMMIT_SHORT_SHA}" docker stack deploy -c deploy/docker-swarm.yml gf-test
